// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"gg/app/dao"
)

// Injectors from wire.go:

func MakeUser() *User {
	user := dao.MakeUser()
	controllerUser := NewUser(user)
	return controllerUser
}
