// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dao

// Injectors from wire.go:

func MakeUser() *User {
	db := NewDb()
	user := NewUser(db)
	return user
}
